# Header
menu:
    home: /
    archive_a: /archives
    categories: /categories
    tags: /tags
    about: /about
    friend: /friends
    #gallery: /gallery
# Head
favicon: /imgs/favicon.png # your favicon png
# Header
avtor: /imgs/logo.png
# if the value of avtor is false
say: Welcome to XXX's Blog

# background_image
# img/01.jpg
# https://source.unsplash.com/collection/954550/1920x1080
background_image:
    enable: true
    #url: https://source.unsplash.com/collection/954550/1920x1080
    #url: img/2.jpg
    #custom Radom img: https://XXX-youname-XXX.github.io/Random-img/
    #customRadom_url: 
    
# show the motto
# otherwise It shows the site description
motto: true

# index-style: pure or cart
index_style: pure

# index_cart_cover
cover: img/cart_cover.jpg

# Page
page_name:
    enable: true

# Post
# Post comment
comment:
    enable: true
# Gittalk settings
gitalk:
    enable: false
    clientID: '3333.... ' 
    clientSecret: '3333.... ' 
    repo: annie-gitalk 
    owner: Sariay 
    admin: Sariay 
    # Must true
    distractionFreeMode: true
    # 去除 more、index.html、?query=123等格式尾部 
    hrefTrimend: '#.*$,\\?.*$,index.html$' 
# Valine settings  
valine: 
    enable: false
    appid: '3333....'
    appkey: '3333......'
    #placeholder： comment
    placeholder: no any!

# Disqus settings
disqus: 
    enable: false
    disqus_username:  # set your disqus name here

# Use livere
livere:
    enable: true
    livere_uid:  # set your livere uid here
    

# Post toc
post_toc:
    enable: true
    number: false

# Post share by addthis
addthis:
    enable: true
    addthis_id:  # set your addthis id here

# friends
friends: [
        {
              title: "Dinghow",
              img: /img/friends/dinghow.jpg,
              href: "https://dinghow.site"
        },
]

# footer
# social
social:
    enable: true
    github: 
    weibo: 
    email: mailto:
    qq: 
    twitter: 

#copyright  
since: 2017
cotent_author: 

#others 
#rss
rss: /atom.xml

#gallery 
#format: natural or square
gallery_format: natural
#one time to load 4 rows or other count(0,1,2,3,4,5,6......)
gallery_limit: 4
#data url
gallery_data: gallery/data.json

# Local search
# Dependencies: https://github.com/flashlab/hexo-generator-search
local_search:
    enable: true
    # if auto, trigger search by changing input
    # if manual, trigger search by pressing enter key or search button
    trigger: auto
    # show top n results per article, show all results by setting to -1
    top_n_per_article: 2

#when click, emerge heart
love:
    enable: false

#totop
#enable.true to use totop 
totop:
    enable: true